config/routes.rb
Likeit::Application.routes.draw do

  resources :product_promotions
  resources :users 
  resource :sessions, only: [:new, :create, :destroy]

  resources :companies
  resources :products

  root 'welcome#index', as: :welcome
  match '/sign_up', to: 'companies#new', via: 'get'

  match '/sign_in', to: 'sessions#new', via: 'get'

  match 'auth/:provider/callback', to: 'user_sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'user_signout', to: 'user_sessions#destroy', as: 'user_signout', via: [:get, :post]

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :product_promotions, foreign_key: "promoter_id"
	has_many :promoting_products, through: :product_promotions
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

	def self.from_omniauth(auth)
		where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
		user.provider = auth.provider
		user.uid = auth.uid
		user.name = auth.info.name
		user.oauth_token = auth.credentials.token
		user.oauth_expires_at = Time.at(auth.credentials.expires_at)
		user.save!
    	end
  	end

	def facebook
		@facebook ||= Koala::Facebook::API.new(oauth_token)
	end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  	@products = current_user.promoting_products
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@products = current_user.product_promotions.paginate(:page => params[:page], :per_page => 12)
  end

  def create
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="row">
    <div class="large-12 columns">
      <div class="panel">

    <% if current_user %>
    <h3 id ="welcomeh3">Welcome <strong><%= current_user.name %></strong>!</h3>
    <%= link_to "Sign out", user_signout_path, id: "sign_out", class: "button radius", style: "float:right" %>
    <%= link_to "General Listing", products_path, class: "button radius", style: "float:right"%>
    <% else %>
    <% end %>
  </div>
</div>


  
    <% @products.each do |p| %>
        <div class="large-6 columns small-6">
                <%=form_for p, :html => { :multipart => true } do |f|%>
               <% if p.image_file_name %>
               <h4><%= p.promoting_product.name %></h4>
                 <%= image_tag p.image.url(:medium), class: "product", style: "float: left"%>
                <div class="fb-share-button" data-href="<%=p.image.url%>" data-width="80px" data-type="box_count"></div>
               <% else %>
                 Upload a Picture!
                <%= f.file_field :image, class: 'form-control' %>
               <%= f.submit "Add a New Creation!", class: 'button tiny radius'%>
               <% end %>
            <%= link_to 'delete', product_promotion_path(p), method: :delete %>

        </div>
            <%end%> 

          <%end%>

      </div>


<script type="text/javascript">
  $(function(){
    baseUrl = location.href.substring(0, location.href.lastIndexOf("/"));
    $(".fb-share-button").each(function(){
      $(this).attr("data-href", baseUrl + $(this).attr("data-href"));
      console.log($(this).attr("data-href"));
    });
  });
</script>