config/routes.rb
Likeit::Application.routes.draw do

  resources :product_promotions
  resources :users 
  resource :sessions, only: [:new, :create, :destroy]

  resources :companies
  resources :products

  root 'welcome#index', as: :welcome
  match '/sign_up', to: 'companies#new', via: 'get'

  match '/sign_in', to: 'sessions#new', via: 'get'

  match 'auth/:provider/callback', to: 'user_sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'user_signout', to: 'user_sessions#destroy', as: 'user_signout', via: [:get, :post]

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<!-- 
<section id="slide-1" class="homeSlide">
    <div class="bcg"
        data-center="background-position: 50% 0px;"
        data-top-bottom="background-position: 50% -100px;"
        data-anchor-target="#slide-1"
    >
        <div class="hsContainer">
            <div class="hsContent"
                data-center="opacity: 1"
                data-106-top="opacity: 0"
                data-anchor-target="#slide-1 h2"
            >
                <h2>Fade out elements before <br>they leave viewport</h2>
            </div>
        </div>
    </div>
</section>
  -->



	<div class = "sectionbox" id="introbox" data-0="background-color:rgb(60,70,97);" data-500="background-color:rgb(255,255,255);">
		<h1> Like it? </h1>
		<h2> Advertise through your own Social Network.</h2>
		<h2> Quick. Easy. Painless </h2>
        
	</div>




<div class = "sectionbox" id="introbox" data-0="background-color:rgb(255,255,255);" data-600="background-color:rgb(60,70,97);">

    <div class ="minibox" id="firstmini"><p>Utilize your personal connections</p></div>
    <hr>
    <div class ="minibox" id="secondmini"><p>Reward Advertisers!</p></div>
    </div>



<div class = "sectionbox" id="whoarewe" data-1000="background-color:rgb(255,255,255);" data-1500="background-color:rgb(235,239,255);">
        <div class= "signupin">
	          <h2><%= link_to "Sign Up for Company", sign_up_path, :class => "sign" %> <h2>
                <h4><em> Already have an account?</em> <%= link_to "Sign in Here!", sign_in_path %> <h4>
        </div>

        <div class= "signupin">
	          <h2><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %> <h2>
	   </div>
    </div>

    