config/routes.rb
Likeit::Application.routes.draw do

  resources :product_promotions
  resources :users 
  resource :sessions, only: [:new, :create, :destroy]

  resources :companies
  resources :products

  root 'welcome#index', as: :welcome
  match '/sign_up', to: 'companies#new', via: 'get'

  match '/sign_in', to: 'sessions#new', via: 'get'

  match 'auth/:provider/callback', to: 'user_sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'user_signout', to: 'user_sessions#destroy', as: 'user_signout', via: [:get, :post]

end

app/models/company.rb
class Company < ActiveRecord::Base

  has_many :products, dependent: :destroy

	attr_accessor :password

	 validates :name, presence: true, length: { maximum: 50 }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

    validates :password, presence: true, length: { minimum: 6 }

    #validate confirmation of password
    # validates_confirmation_of :password, message: "confirmation does not match"
    # validates_presence_of :password_confirmation, if: :password_changed?
    
  	#hash the password before user data saved
  	before_save :hash_password

    validates :password, :presence =>true, :confirmation => true, :length => { :within => 6..40 }, :on => :create

    validates :password, :confirmation => true, :length => { :within => 6..40 }, :on => :update, :unless => lambda{ |user| user.password.blank? } 
    #hash the password before user data saved
    before_save :hash_password

    #downcase all email to quarantee its uniqueness
    before_save { self.email = email.downcase }

  	def authenticate(password)
  		self.password_digest == BCrypt::Engine.hash_secret(password, self.salt)
  	end

  	private
  	# method to generate store salt, hash user password, set password field nil since no such attribute in database
  	def hash_password
  		self.salt = BCrypt::Engine.generate_salt
  		self.password_digest = BCrypt::Engine.hash_secret(self.password, self.salt)
  		self.password = nil
  	end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
		before_action :set_company, :only => [:show, :edit, :update, :destroy]
		before_action :correct_company, :only => [:show, :edit, :update, :destroy]
		respond_to :html, :json	


	

	def index
		@companies = Company.all.order("name desc")
		respond_with @companies

	end

	def new
		@company = Company.new
	end


  def create
    @company = Company.new(company_params)

    if @company.save
    	session[:remember_token] = @company.id
      	respond_to do |format|
        format.html { redirect_to @company }
        format.json { render json: @company, status: :created }
      end
    else
      respond_to do |format|
        format.html { render 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

	def show
	end


	def edit
	end

	def update
		if @company.update(company_params)
			respond_to do |format|
				format.html { redirect_to @company}
				format.json { render nothing: true, status: :no_content}
		end
	else 
		respond_to do |format|
			format.html {render 'new'}
			format.json {render json: @company.errors, status: :unprocessable_entity}
			end
		end
	end


	def destroy
		@company.destroy

		respond_to do |format|
			format.html {redirect_to company}
			format.json { render json: { head: :ok }}
		end
	end
	

protected

def set_company
	@company = Company.find(params[:id])
end

def correct_company
	redirect_to sign_in_path unless current_company == Company.find(params[:id])
end

def company_params
	params.require(:company).permit(:name, :email, :url, :mission, :password, :password_confirmation, :image)
end



end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
		before_action :set_company, :only => [:show, :edit, :update, :destroy]
		respond_to :html, :json	
end

	

	def index
		@companies = Company.all.order("name desc")
		respond_with @companies

	end

	def new
		@company = Company.new
	end


  def create
    @company = Company.new(question_params)

    if @company.save
      respond_to do |format|
        format.html { redirect_to questions_path }
        format.json { render json: @company, status: :created }
      end
    else
      respond_to do |format|
        format.html { render 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

	def show
		respond_with @company
	end


	def edit
	end

	def update
		if @company.update(company_params)
			respond_to do |format|
				format.html { redirect_to companies_path}
				format.json { render nothing: true, status: :no_content}
		end
	else 
		respond_to do |format|
			format.html {render 'edit'}
			format.json {render json: @company.errors, status: :unprocessable_entity}
		end
	end
end


	def destroy

		@company.destroy

		respond_to do |format|
			format.html {redirect_to company}
			format.json { render json: { head: :ok }}
		end
	end
	

protected

def set_company
	@question = Question.find(params[:id])
end

def company_params
	params.require(:company).permit(:name, :email, :url, :mission, :password, :password_confirmation)
end



end

app/helpers/company_helper.rb
module CompanyHelper
end

app/views/companies/edit.html.erb
<% provide(:title, 'Edit your company account settings!') %>

<%= form_for @company, html: { class: "signupform" } do |c| %>
	<p>Edit Settings!</p>
	<%= render 'shared/error_messages' %>

		<div class ="formfield">Company Name:</div> 
		<div><%= c.text_field :name %> </div>
		<div class ="formfield">Edit your company URL:</div> 
		<div><%= c.text_field :url %> </div>
		<div class ="formfield">Email:</div>
		<div> <%= c.text_field :email %> </div>
		<div class ="formfield">Password</div>
		<div> <%= c.password_field :password %> </div>
		<div class ="formfield">Confirm Password</div>
		<div> <%= c.password_field :password_confirmation %> 
		</div>
			<%= c.submit 'Submit', class: "button primary small" %> <%= link_to "Cancel", company_path(current_company), class: "button secondary small" %>

<%end%>

app/views/companies/new.html.erb
<% provide(:title, 'Create your account!') %>
<%= form_for @company, html: { class: "signupform" } do |c| %>
	<%= render 'shared/error_messages' %>
		<div class ="formfield">Company Name:</div> 
		<div><%= c.text_field :name %> </div>
		<div class ="formfield">Edit your company URL:</div> 
		<div><%= c.text_field :url %> </div>
		<div class ="formfield">Email:</div>
		<div> <%= c.text_field :email %> </div>
		<div class ="formfield">Password</div>
		<div> <%= c.password_field :password %> </div>
		<div class ="formfield">Confirm Password</div>
		<div> <%= c.password_field :password_confirmation %> 
		</div>
			<%= c.submit 'Submit', class: "button primary small" %> <%= link_to "or Sign in", new_sessions_path %>

<%end%>

app/views/companies/show.html.erb
<div class = "companycontainer">
        <aside class="aside ">
          <h4>Welcome <%= @company.name.upcase %></h4>
          <div>
            <%= link_to "Account setting", edit_company_path, :class => "button expand"%>
            <%= link_to "Add a product", new_product_path, :class => "button expand"%>
            <%= link_to "Sign Out", sessions_path, method: :delete, :class => "button expand"%>
          </div>
        </aside>
      
 <div class ="companyrow">
    <h1> Your Products </h1>
          <% @company.products.each do |p| %>
            <div class="testing">
                <h3><%= link_to p.name, p %></h3>
                  <%= image_tag p.image.url(:medium), class: "productimage"%>
                <div class = "productbox">
                      <span class = "producttitles">Description:</span>  <span class = "text"><%= p.description %></span><br><br>
                      <span class = "producttitles">Reward:</span> <span class = "text"><%= p.reward %></span><br><br>
                      <span class = "producttitles">Requirement:</span> <span class = "text"><%= p.requirement %> likes<br><br>
                      <span class = "producttitles">Promoted by:</span> <span class = "text"><%= link_to p.product_promotions.count, p %> people<br><br>
                     <span><%= link_to 'Edit', edit_product_path(p) %> | 
                    <%= link_to 'Delete', product_path(p), method: :delete, data: { confirm: "Delete #{p.name} ?" } %></span>
                    <br>
                </div>
              </div>
          <% end %>            
          </div> 
          


<!--               <footer class="row">
                 <div class="large-12 columns"><hr/>
                    <div class="row">
                      <div class="large-6 columns">
                    <p>© Copyright no one at all. Go to town.</p>
                  </div>
                </div>
              </div>
            </footer> -->

     </div>