config/routes.rb
Likeit::Application.routes.draw do

  resources :product_promotions
  resources :users 
  resource :sessions, only: [:new, :create, :destroy]

  resources :companies
  resources :products

  root 'welcome#index', as: :welcome
  match '/sign_up', to: 'companies#new', via: 'get'

  match '/sign_in', to: 'sessions#new', via: 'get'

  match 'auth/:provider/callback', to: 'user_sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'user_signout', to: 'user_sessions#destroy', as: 'user_signout', via: [:get, :post]

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :company
  has_many :product_promotions, foreign_key: "promoting_product_id"
  has_many :promoters, through: :product_promotions

  #set default order to show created newest first
  default_scope -> { order("created_at DESC") }

  validates :name, presence: true, length: { maximum: 50 }

  validates :requirement, presence: true, :numericality => { :greater_than => 0, :less_than_or_equal_to => 1000000 }

  validates :reward, presence: true, length: { maximum: 50 }

  #ensure all products must be associated with a company
  validates :company_id, presence: true
  has_attached_file :image, :styles => { :medium => "300x300>", :large => "600x600>" }, :default_url => "/images/:style/missing.png", :storage => :s3, :bucket => 'ericaaronbucket'
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  # validates_attachment_presence :image
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']

  def promoting?(user)
    product_promotions.find_by(promoter_id: user.id)
  end

  def promote_this!(user)
    product_promotions.create!(promoter_id: user.id)
  end

  def unpromote!(user)
    product_promotions.find_by(promoter_id: user.id).destroy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :signed_in_company, :except =>[:show, :index]
    before_action :correct_company, :only => [:destroy]
    before_action :set_product, :only => [:edit, :update, :show, :destroy]
    respond_to :html, :json 
    


  def index
    @products = Product.paginate(:page => params[:page], :per_page => 12)
    respond_with @products 
  end

  def new
@product = current_company.products.new
  end


  def create
      @product = current_company.products.new(product_params)
    if @product.save
      respond_to do |format|
        format.html { redirect_to current_company }
        format.json { render json: @product, status: :created }
      end
    else
      respond_to do |format|
        format.html { render 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @promotions = @product.product_promotions
  end


  def edit

  end

  def update
    if @product.update_attributes(product_params)
        respond_to do |format|
          format.html { redirect_to current_company}
          format.json { render nothing: true, status: :no_content}
        end
    else 
      respond_to do |format|
        format.html {render 'edit'}
        format.json {render json: @product.errors, status: :unprocessable_entity}
      end
    end
  end


  def destroy

    @product.destroy

    respond_to do |format|
      format.html {redirect_to current_company}
      format.json { render json: { head: :ok }}
    end
  end
  

protected

def set_product
  @product = Product.find(params[:id])
end

def product_params
  params.require(:product).permit(:name, :requirement, :reward, :description, :company_id, :image)
end

    def correct_company
      @products = current_company.products.find_by(id: params[:id])
      redirect_to root_url if @products.nil?
    end



end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :html => { :multipart => true } do |f| %>

  <%= f.file_field :image, class: 'form-control' %>
  <p>Name: <%= f.text_field :name, class: 'form-control', placeholder: 'product name'%></p>
  <p>Rewards: <%= f.text_field :reward, class: 'form-control', placeholder: 'reward'%></p>

  <p>Likes requirement: <%= f.number_field :requirement, class: 'form-control', placeholder: 'likes requirement'%></p>

  <p>Product Description: <%= f.text_area :description, class:'form-control' %></p>
  <%= f.submit "Submit", class: 'button radius small'%>
  <%= link_to 'Cancel', company_path(current_company), class: "button secondary small" %>
<% end %> 

app/views/products/edit.html.erb
<fieldset>
	<legend>Edit Product</legend>
	<%= render "form" %>
</fieldset> 

app/views/products/index.html.erb
<div class="row">
    
          <nav class="top-bar">
            <ul>            
              <li class="left">
                    General Listing
              </li>
              <% if current_user %>
               <li class="right"><%= link_to "Sign out", user_signout_path, id: "sign_out" %></li>
              <li class="right"><%= link_to "Your profile", users_path %></li>
                <%end%>
            </ul>
          </nav>
                   


          
            <% @products.each do |p|%>
            <div class="large-3 medium-6 small-12 columns">
                    <%= link_to image_tag(p.image.url(:medium)), p,class: "product"%>

                    <div class="panel" style="margin-bottom:0px">Name: <%=p.name%></div>
      		          <div class="panel" style="margin-bottom:0px">Need: <%=p.requirement%> likes</div>
      			        <div class="panel" style="margin-bottom:0px">Rewards: <%=p.reward%></div>

                    
                    <% if p.promoting?(current_user) %>
                    <p class ="promotedbutton"> Promoting!</p>
                    <% else %>
                      <%= form_for :product_promotion, :url => product_promotions_path do |f| %>
                      <%= f.hidden_field :promoting_product_id, :value => p.id %>
                      <%= f.submit 'Promote This', :class => "productsbutton" %>
                      <% end %>
                      <% end %>
              </div>
            <%end%>

          
    
      
      <%= will_paginate @products %>
      

  </div>

app/views/products/new.html.erb
	<fieldset>
	<legend>Add New Product</legend>
	<%= render "form" %>
</fieldset> 

app/views/products/show.html.erb
<div class="row">
	<% if current_company %>
	<%= link_to "Home", company_path(current_company) %> | <%= link_to 'Sign out', sessions_path, method: :delete %>
	<% end %>
</div>

<div class="row">
	<h4><%= @product.name %> by <%= @product.company.name %></h4>
	<div class="large-5 columns">
		<div class="th">  
			<%= image_tag @product.image.url(:medium)%>
		</div>
		<p>Product Description: <%=@product.description %></p>
		<p>Reward: <%= @product.reward %></p><br/>
		<p>Requirement: <%= @product.requirement %></p>
	</div>

	
	<div class = "large-7 columns" id ="promotersbox">
		<% @promotions.each do |promotion| %>
			<% if promotion.image_file_name %>
			
				<div class = "th">
				<%= image_tag promotion.image.url(:thumb) %>
				Promoted by <%= promotion.promoter.name %>

			</div>
		
		<% end %>	
	<% end %>
	</div>



</div>